### ISSUE TITLE
Readme fix + test size

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-FordProg-2020-Morse#1]
Use 3 backticks for grammar to render properly, and make a table for the test results.
https://guides.github.com/features/mastering-markdown/

Run the test with a much larger input file. It is even better, if there are 20 different sizes which scale up in size.

**Comment by hegyhati** [comment]
One more thing: I don't see it mentioned anywhere, that the 3 parsers produced the same results. It should be checked of course.

**Comment by srichard95** [comment]
The solutions executed with much larger file. The result is available at the readme.md.

The readme.md styling fixed.
