### ISSUE TITLE
Solution1 issues

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-FordProg-2020-Morse#2]
Non-terminals are usually with small letters by convention.

Also, it would probably be much easier, if the non-terminal would have been named like this:

```
message: char message
    | 
     ;

char:  ROVID r
    | HOSSZU h
    | SZOKOZ s

s: BREAK { AddChar(' '); };

r:  ROVID rr
    | HOSSZU rh
    | BREAK { AddChar('E'); };
rr: ROVID rrr 
    | HOSSZU rrh
    | BREAK  { AddChar('I'); };
```

I.e., the name of the terminal should somehow give a clue about what it represents. of course, `dot-dot-dash` is a better name than `rrh` 

Also, if everything is in English, it is probably better to use English terms for the names of tokens, non-terminals as well.

**Comment by srichard95** [comment]
Issue #2  fixed.
- English names used for tokes
- Non-terminals with small letters
- Non-terminals naming convection updated accroding to the sample.

"dot-dot-dash" would result long names, thus i used like "s sl ssl" (s- short, l - long)
