### ISSUE TITLE
Solution 3 issues

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-FordProg-2020-Morse#3]
Just get rid of the grammar file as it is, and in the lexer use `Addchar` instead of `return`.

**Comment by srichard95** [comment]
Issue #3 fixed.

- Only lexer is used for parsing. Grammar.y removed.

**Comment by hegyhati** [comment]
@srichard95  meg azt csinald meg, hogy a generalt fajlok ne legyenek benne a repoban, aztan mehet a merge.
